# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Cliente.create(id: 42, nome: "Silvia")
Cliente.create(id: 100, nome: "Antonio")
Cliente.create(id: 101, nome: "Tania")
Cliente.create(id: 121, nome: "Fatima Maria")
Cliente.create(id: 155, nome: "Mara Rubia")
Cliente.create(id: 293, nome: "Cristina")
Cliente.create(id: 307, nome: "Maria")
Cliente.create(id: 314, nome: "Cecilia")
Cliente.create(id: 342, nome: "Simone")
Cliente.create(id: 357, nome: "Ricardo")
Cliente.create(id: 376, nome: "Maria Nazareth")
Cliente.create(id: 386, nome: "Julio")
Cliente.create(id: 403, nome: "Fabiane")
Cliente.create(id: 406, nome: "Matheus")
Cliente.create(id: 408, nome: "Lucimauro")
Cliente.create(id: 412, nome: "Maria Angela")
Cliente.create(id: 413, nome: "Ivaneide")
Cliente.create(id: 414, nome: "Gesiel")
Cliente.create(id: 415, nome: "Patricia")
Cliente.create(id: 418, nome: "Gisele")
Cliente.create(id: 423, nome: "Renato")
Cliente.create(id: 438, nome: "Luiz Fernando")
Cliente.create(id: 439, nome: "Denise")
Cliente.create(id: 441, nome: "Adiel")
Cliente.create(id: 444, nome: "Sira")
Cliente.create(id: 447, nome: "Edna")
Cliente.create(id: 450, nome: "Fabiana")
Cliente.create(id: 457, nome: "Karen")
Cliente.create(id: 458, nome: "Norma")
Cliente.create(id: 464, nome: "Joao")
Cliente.create(id: 465, nome: "Raul")
Cliente.create(id: 466, nome: "Renata")
Cliente.create(id: 467, nome: "Adriana")
Cliente.create(id: 468, nome: "Maria Elizabeth")
Cliente.create(id: 470, nome: "Reinaldo")
Cliente.create(id: 477, nome: "Marjory")
Cliente.create(id: 478, nome: "Rayane")
Cliente.create(id: 479, nome: "Danilson")
Cliente.create(id: 481, nome: "Jessica")